### ISSUE TITLE
Integration with browsers

### ISSUE THREAD

**Issue by iG8R** [sourabhkv/ytdl#16]
Is it possible to make integration with browsers, e.g. Firefox?
For instance, if ytdl could receive  CLI arguments it would be possible to pass an URL from the browser to ytdl through such addons as [https://addons.mozilla.org/en-US/firefox/addon/open-with/](https://addons.mozilla.org/en-US/firefox/addon/open-with/) or [https://addons.mozilla.org/en-US/firefox/addon/yadattawa/](https://addons.mozilla.org/en-US/firefox/addon/yadattawa/)

**Comment by sourabhkv** [comment]
Maybe it is possible to have such integrations
I have not worked on Firefox addons , you can have a browser built from PySide6 and make changes accordingly
As of now no plans to do such integrations
