### ISSUE TITLE
Best Audio & Best Video option

### ISSUE THREAD

**Issue by Useless-Panda** [sourabhkv/ytdl#2]
Hi ! How are you ?
Can you add best video & best audio option in Video steams and Audio streams

**Comment by sourabhkv** [comment]
Wait for next version it will be added

**Comment by Useless-Panda** [comment]
That's awesome! Thanks
also can you add the option to save description in comments where video url is being saved.

**Comment by sourabhkv** [comment]
The formats are sorted according to size and the streams which might throttle are also marked (YouTube only)

**Comment by Useless-Panda** [comment]
Thank you
