### ISSUE TITLE
When I try to download videos from this website, it shows the following error

### ISSUE THREAD

**Issue by charles2268** [sourabhkv/ytdl#32]
### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE

- [X] I understand that I will be **blocked** if I remove or skip any mandatory\* field

### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running latest version of [ytdl](https://github.com/sourabhkv/ytdl/releases/latest/) ([update instructions](https://github.com/yt-dlp/yt-dlp#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've searched the [bugtracker](https://github.com/sourabhkv/ytdl/issues?q=) for similar issues **including closed ones**. DO NOT post duplicates

### Provide a description that is worded well enough to be understood

https://www.youtube.com/playlist?list=PLE68oggiDuAlI7N1CX9KgzlvGgZ9mfE3I
 When I try to download videos from this website, it shows the following error. Could you please help me identify the reason? Thank you.
![image](https://github.com/sourabhkv/ytdl/assets/39716978/fa2da406-9236-4bcc-908b-6285378c7487)
![image](https://github.com/sourabhkv/ytdl/assets/39716978/9382de81-444b-4f7a-876a-36df5c8b7445)

**Comment by sourabhkv** [comment]
Go to custom command you will find `Terminal` option, click on it, it will launch cmd , then type the following
```
yt-dlp_x86 -U
```
It will update yt-dlp
Then try downloading the video.

**Comment by charles2268** [comment]
Thank you, it resolved my problem.
