### ISSUE TITLE
How to download specific part of YouTube video? 

### ISSUE THREAD

**Issue by perrypinaki** [sourabhkv/ytdl#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sourabhkv** [comment]
You can download specific part of video by modifying settings

Open settings add option `--download-sections *1:10-2:20` 

Syntax `--download-sections *<start time>-<end time>`
Then **Save** the options. Then try downloading.

![image](https://user-images.githubusercontent.com/55890376/179402224-cf5ffb3d-4089-4989-9c7a-69f9342e6d36.png)

**Note : THIS IS TEMPORARY SOLUTION , DOWNLOAD PROGRESS MAY NOT BE AVAILABLE IF USED THIS OPTION ONLY POP UP MESSAGE WILL BE SHOWN AFTER DOWNLOAD COMPLETION.**

Wait for future updates .
