### ISSUE TITLE
Use Regex in output templates

### ISSUE THREAD

**Issue by perrypinaki** [sourabhkv/ytdl#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
 Ytdl gui seems to work with no issue for me now. Wasn't so in earlier builds. 1 question. Is it possible to assign custom file name template to PLAYLISTS downloads? Like adding $num to file names in playlist, so videos start with 01-VideoX; 02-VideoY, etc

**Comment by sourabhkv** [comment]
![image](https://user-images.githubusercontent.com/55890376/190460719-29b901a0-c409-4c71-b982-cc53e5afe8eb.png)

Work in Progress.
