### ISSUE TITLE
no power to resume after pause

### ISSUE THREAD

**Issue by KalpanaChetan** [sourabhkv/ytdl#7]
1.please add scheduler

2.Download video from a playlist in this method

Create a folder (channel name) and create another folder (playlist name)  inside it and a third folder (video number)  inside it
Video has to be downloaded in third folder
Create a third folder (video number) for each video

**Comment by sourabhkv** [comment]
1. Scheduler is coming to ytdl unlocked version
2. Change default output template for playlist to `%(uploader)s/%(playlist_title)s/%(playlist_index)s/%(title)s.%(ext)s` and save it

![image](https://user-images.githubusercontent.com/55890376/195983155-90b89e4a-6f40-4436-a6bd-cb4010fbac4d.png)

**Comment by sourabhkv** [comment]
If you want to use scheduler now then you can use Task scheduler
Step 1: Add `C:\Users\soura\AppData\Local\Youtube-dl GUI\Youtube-dl GUI` to Path
Step 2: Add task to Task scheduler with parameters like URL, output, format . . .
Remember you have to change parameters each time manually.

**Comment by KalpanaChetan** [comment]
No option

![Screenshot (1).png](https://user-images.githubusercontent.com/112402936/195986718-1e4d2e63-ce5d-47a2-adaa-bc57f8b26ca6.png)

**Comment by sourabhkv** [comment]
You are using old version

**Comment by sourabhkv** [comment]
Wait for a few days for a newer version

**Comment by KalpanaChetan** [comment]
Ok

**Comment by sourabhkv** [comment]
Fixed in #28
This works if application is open
